In [7]:
#loading the libaries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from PIL import Image
from wordcloud import WordCloud, STOPWORDS, ImageColorGenerator

import matplotlib.pyplot as plt

In [33]:
#loading the data
df=pd.read_csv('wiki_movie_plots_deduped_cleaned_genre_and_plot.csv')
df

,Release Year,Title,Origin/Ethnicity,Director,Cast,Genre,Genre_updated,Wiki Page,Plot,Plot_cleanned
0,1901,Kansas Saloon Smashers,American,Unknown,NaN,unknown,NaN,https://en.wikipedia.org/wiki/Kansas_Saloon_Sm...,"A bartender is working at a saloon, serving dr...",bartender working saloon serving drink custome...
1,1901,Love by the Light of the Moon,American,Unknown,NaN,unknown,NaN,https://en.wikipedia.org/wiki/Love_by_the_Ligh...,"The moon, painted with a smiling face hangs ov...",moon painted smiling face hang park night youn...
2,1901,The Martyred Presidents,American,Unknown,NaN,unknown,NaN,https://en.wikipedia.org/wiki/The_Martyred_Pre...,"The film, just over a minute long, is composed...",film minute long composed two shot first girl ...
3,1901,"Terrible Teddy, the Grizzly King",American,Unknown,NaN,unknown,NaN,"https://en.wikipedia.org/wiki/Terrible_Teddy,_...",Lasting just 61 seconds and consisting of two ...,lasting second consisting two shot first shot ...
4,1902,Jack and the Beanstalk,American,"George S. Fleming, Edwin S. Porter",NaN,unknown,NaN,https://en.wikipedia.org/wiki/Jack_and_the_Bea...,The earliest known adaptation of the classic f...,earliest known adaptation classic fairytale fi...
...,...,...,...,...,...,...,...,...,...,...
42530,2014,The Water Diviner,Turkish,Director: Russell Crowe,Director: Russell Crowe\r\nCast: Russell Crowe...,unknown,NaN,https://en.wikipedia.org/wiki/The_Water_Diviner,"The film begins in 1919, just after World War ...",film begin wxyz world war ended centre around ...
42531,2017,Çalgı Çengi İkimiz,Turkish,Selçuk Aydemir,"Ahmet Kural, Murat Cemcir",comedy,comedy,https://en.wikipedia.org/wiki/%C3%87alg%C4%B1_...,"Two musicians, Salih and Gürkan, described the...",two musician salih gürkan described adventure ...
42532,2017,Olanlar Oldu,Turkish,Hakan Algül,"Ata Demirer, Tuvana Türkay, Ülkü Duru",comedy,comedy,https://en.wikipedia.org/wiki/Olanlar_Oldu,"Zafer, a sailor living with his mother Döndü i...",zafer sailor living mother döndü coastal villa...
42533,2017,Non-Transferable,Turkish,Brendan Bradley,"YouTubers Shanna Malcolm, Shira Lazar, Sara Fl...",romantic comedy,comedy,https://en.wikipedia.org/wiki/Non-Transferable...,The film centres around a young woman named Am...,film centre around young woman named amy tyler...
42534,2017,İstanbul Kırmızısı,Turkish,Ferzan Özpetek,"Halit Ergenç, Tuba Büyüküstün, Mehmet Günsür, ...",romantic,romance,https://en.wikipedia.org/wiki/%C4%B0stanbul_K%...,The writer Orhan Şahin returns to İstanbul aft...,writer orhan şahin return i̇stanbul many year ...

In [34]:
# we are using counter for counting the number of times a particaular word occurs
from collections import Counter

In [35]:
#Counter(" ".join(df[df['Genre_updated']=='romance']['Plot_cleanned']).split()).most_common(500)

In [36]:
#list of the unique genres
choices_final=df['Genre_updated'].unique()[1:]
choices_final

array(['western', 'comedy', 'short', 'action', 'crime', 'biography',
       'drama', 'adventure', 'fantasy', 'sports', 'horror', 'historical',
       'documentary', 'serial', 'mystery', 'romance', 'war', 'spy',
       'animated', 'family', 'thriller', 'musical', 'sci_fi', 'noir',
       'martial_arts', 'teen', 'social', 'anime'], dtype=object)

In [44]:
%%time
# for making the list of most common words like 30, 50, 100 for a particular genre
dax={choices:Counter(" ".join(df[df['Genre_updated']==choices]['Plot_cleanned']).split()).most_common(200) for choices in choices_final}

Wall time: 1.53 s

In [45]:
data=pd.DataFrame(columns = ['Genre', 'Words', 'Counts'])
for i in dax.keys():
    df1=pd.concat([pd.DataFrame([i for j in range(len(dax[i]))],columns=['Genre']),pd.DataFrame(dax[i],columns=['Words', 'Counts'])],axis=1)
    data=pd.concat([data,df1])

In [46]:
data

       Genre      Words Counts
0    western       town   1144
1    western        men    940
2    western       take    683
3    western       back    672
4    western        one    671
..       ...        ...    ...
195    anime       tima     35
196    anime    leaving     34
197    anime        age     34
198    anime  destroyed     34
199    anime     behind     34

[5600 rows x 3 columns]

In [47]:
data.to_csv("most_frequent_words_200.csv",index=False)

In [11]:
'''font = {'family': 'serif',
            'weight': 'normal',
            'size': 50,
            }

for i in choices_final:
    
    word_cloud = WordCloud(width = 1000, height = 1000,background_color ='white').generate(" ".join(title for title in data[data['Genre']==i]['Words']))
    plt.figure(figsize = (20, 35), facecolor = None)
    plt.imshow(word_cloud, interpolation='bilinear')
    plt.axis("off")
    plt.title('-'*20+i.upper()+'-'*20,fontdict=font)
    plt.show()
    print('\n')
'''

'font = {\'family\': \'serif\',\n            \'weight\': \'normal\',\n            \'size\': 50,\n            }\n\nfor i in choices_final:\n    \n    word_cloud = WordCloud(width = 1000, height = 1000,background_color =\'white\').generate(" ".join(title for title in data[data[\'Genre\']==i][\'Words\']))\n    plt.figure(figsize = (20, 35), facecolor = None)\n    plt.imshow(word_cloud, interpolation=\'bilinear\')\n    plt.axis("off")\n    plt.title(\'-\'*20+i.upper()+\'-\'*20,fontdict=font)\n    plt.show()\n    print(\'\n\')\n'